# Makefile generated by MakefileGenerator.cs
# *DO NOT EDIT*

UNREALROOTPATH = /opt/UnrealEngine5.5.1

TARGETS = \
	FishinformationGame-Android-DebugGame  \
	FishinformationGame-Android-Development  \
	FishinformationGame-Android-Shipping  \
	FishinformationGame-Linux-DebugGame  \
	FishinformationGame-Linux-Development  \
	FishinformationGame-Linux-Shipping  \
	FishinformationGame-LinuxArm64-DebugGame  \
	FishinformationGame-LinuxArm64-Development  \
	FishinformationGame-LinuxArm64-Shipping  \
	FishinformationGame \
	FishinformationGameEditor-Linux-DebugGame  \
	FishinformationGameEditor-Linux-Development  \
	FishinformationGameEditor \
	LiveLinkHub-Linux-DebugGame  \
	LiveLinkHub-Linux-Development  \
	LiveLinkHub \
	DotNetPerforceLib \
	EventLoopUnitTests \
	UnrealEditor-Linux-DebugGame  \
	UnrealEditor-Linux-Development  \
	UnrealEditor \
	UnrealGame-Android-DebugGame  \
	UnrealGame-Android-Development  \
	UnrealGame-Android-Shipping  \
	UnrealGame-Linux-DebugGame  \
	UnrealGame-Linux-Development  \
	UnrealGame-Linux-Shipping  \
	UnrealGame-LinuxArm64-DebugGame  \
	UnrealGame-LinuxArm64-Development  \
	UnrealGame-LinuxArm64-Shipping  \
	UnrealGame\
	configure

BUILD = "$(UNREALROOTPATH)/Engine/Build/BatchFiles/RunUBT.sh"

all: StandardSet

RequiredTools: CrashReportClient-Linux-Shipping CrashReportClientEditor-Linux-Shipping ShaderCompileWorker UnrealLightmass EpicWebHelper-Linux-Shipping

StandardSet: RequiredTools UnrealFrontend FishinformationGameEditor UnrealInsights

DebugSet: RequiredTools UnrealFrontend-Linux-Debug FishinformationGameEditor-Linux-Debug


FishinformationGame-Android-DebugGame:
	 $(BUILD) FishinformationGame Android DebugGame  -Project="/home/bwalters/Development/FishinformationGame/FishinformationGame.uproject" $(ARGS)

FishinformationGame-Android-Development:
	 $(BUILD) FishinformationGame Android Development  -Project="/home/bwalters/Development/FishinformationGame/FishinformationGame.uproject" $(ARGS)

FishinformationGame-Android-Shipping:
	 $(BUILD) FishinformationGame Android Shipping  -Project="/home/bwalters/Development/FishinformationGame/FishinformationGame.uproject" $(ARGS)

FishinformationGame-Linux-DebugGame:
	 $(BUILD) FishinformationGame Linux DebugGame  -Project="/home/bwalters/Development/FishinformationGame/FishinformationGame.uproject" $(ARGS)

FishinformationGame-Linux-Development:
	 $(BUILD) FishinformationGame Linux Development  -Project="/home/bwalters/Development/FishinformationGame/FishinformationGame.uproject" $(ARGS)

FishinformationGame-Linux-Shipping:
	 $(BUILD) FishinformationGame Linux Shipping  -Project="/home/bwalters/Development/FishinformationGame/FishinformationGame.uproject" $(ARGS)

FishinformationGame-LinuxArm64-DebugGame:
	 $(BUILD) FishinformationGame LinuxArm64 DebugGame  -Project="/home/bwalters/Development/FishinformationGame/FishinformationGame.uproject" $(ARGS)

FishinformationGame-LinuxArm64-Development:
	 $(BUILD) FishinformationGame LinuxArm64 Development  -Project="/home/bwalters/Development/FishinformationGame/FishinformationGame.uproject" $(ARGS)

FishinformationGame-LinuxArm64-Shipping:
	 $(BUILD) FishinformationGame LinuxArm64 Shipping  -Project="/home/bwalters/Development/FishinformationGame/FishinformationGame.uproject" $(ARGS)

FishinformationGame: FishinformationGame-Linux-Development

FishinformationGameEditor-Linux-DebugGame:
	 $(BUILD) FishinformationGameEditor Linux DebugGame  -Project="/home/bwalters/Development/FishinformationGame/FishinformationGame.uproject" $(ARGS)

FishinformationGameEditor-Linux-Development:
	 $(BUILD) FishinformationGameEditor Linux Development  -Project="/home/bwalters/Development/FishinformationGame/FishinformationGame.uproject" $(ARGS)

FishinformationGameEditor: FishinformationGameEditor-Linux-Development

LiveLinkHub-Linux-DebugGame:
	 $(BUILD) LiveLinkHub Linux DebugGame  $(ARGS)

LiveLinkHub-Linux-Development:
	 $(BUILD) LiveLinkHub Linux Development  $(ARGS)

LiveLinkHub: LiveLinkHub-Linux-Development

DotNetPerforceLib: DotNetPerforceLib-Linux-Development

EventLoopUnitTests: EventLoopUnitTests-Linux-Development

UnrealEditor-Linux-DebugGame:
	 $(BUILD) UnrealEditor Linux DebugGame  $(ARGS)

UnrealEditor-Linux-Development:
	 $(BUILD) UnrealEditor Linux Development  $(ARGS)

UnrealEditor: UnrealEditor-Linux-Development

UnrealGame-Android-DebugGame:
	 $(BUILD) UnrealGame Android DebugGame  $(ARGS)

UnrealGame-Android-Development:
	 $(BUILD) UnrealGame Android Development  $(ARGS)

UnrealGame-Android-Shipping:
	 $(BUILD) UnrealGame Android Shipping  $(ARGS)

UnrealGame-Linux-DebugGame:
	 $(BUILD) UnrealGame Linux DebugGame  $(ARGS)

UnrealGame-Linux-Development:
	 $(BUILD) UnrealGame Linux Development  $(ARGS)

UnrealGame-Linux-Shipping:
	 $(BUILD) UnrealGame Linux Shipping  $(ARGS)

UnrealGame-LinuxArm64-DebugGame:
	 $(BUILD) UnrealGame LinuxArm64 DebugGame  $(ARGS)

UnrealGame-LinuxArm64-Development:
	 $(BUILD) UnrealGame LinuxArm64 Development  $(ARGS)

UnrealGame-LinuxArm64-Shipping:
	 $(BUILD) UnrealGame LinuxArm64 Shipping  $(ARGS)

UnrealGame: UnrealGame-Linux-Development

configure:
	$(BUILD) -ProjectFiles -Project="/home/bwalters/Development/FishinformationGame/FishinformationGame.uproject" -Game 

.PHONY: $(TARGETS)
